name: 'Packagist Update'
description: 'Notify Packagist to update the package for this repository.'
runs:
  using: 'composite'
  steps:
    - name: Notify Packagist
      shell: bash
      run: |
        set -euo pipefail

        REPO_URL="https://github.com/${{ inputs.repository }}"
        echo "Notifying Packagist for $REPO_URL"

        if [ -n "${{ inputs.token }}" ]; then
          # Use Authorization Bearer token (useful for Packagist.com or token-based APIs)
          echo "Using PACKAGIST_TOKEN (Authorization: Bearer)"
          HTTP_STATUS=$(curl -s -o /tmp/packagist_resp.txt -w "%{http_code}" -X POST "https://packagist.org/api/update-package" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -d "repository[url]=$REPO_URL")
        elif [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.api_token }}" ]; then
          echo "Using PACKAGIST_USERNAME & PACKAGIST_API_TOKEN"
          HTTP_STATUS=$(curl -s -o /tmp/packagist_resp.txt -w "%{http_code}" -X POST "https://packagist.org/api/update-package?username=${{ inputs.username }}&apiToken=${{ inputs.api_token }}" -d "repository[url]=$REPO_URL")
        else
          echo "ERROR: either 'token' or both 'username' and 'api_token' must be provided" >&2
          exit 1
        fi

        echo "Packagist response (status $HTTP_STATUS):"
        cat /tmp/packagist_resp.txt || true
        if [ "$HTTP_STATUS" -ge 400 ]; then
          echo "Packagist update failed with HTTP status $HTTP_STATUS" >&2
          exit 1
        fi
inputs:
  token:
    description: 'Packagist token (preferred). If provided, will be used as an Authorization: Bearer header.'
    required: false
  username:
    description: 'Packagist username (fallback)'
    required: false
  api_token:
    description: 'Packagist API token (fallback)'
    required: false
  repository:
    description: 'owner/repo, e.g. ixys/filament-workflows'
    required: true
