name: 'GitHub Packages Composer Publish'
description: 'Publish a composer ZIP artifact to GitHub Packages (composer). Detects package name/version from composer.json and uploads the provided zip. Includes retry/backoff for transient errors.'

# Inputs must be declared at the top level (sibling to `runs`) for composite actions
inputs:
  package_zip_path:
    description: 'Path or glob to the composer archive zip to upload (e.g. dist/*.zip)'
    required: true
  github_token:
    description: 'GitHub token to use for authentication (defaults to $GITHUB_TOKEN from runner)'
    required: false
  retries:
    description: 'Number of attempts on transient errors (429/5xx)'
    required: false
    default: '3'
  backoff_seconds:
    description: 'Initial backoff in seconds; exponential backoff applied for retries'
    required: false
    default: '5'
  repository_owner:
    description: 'Repository owner (optional, will use $GITHUB_REPOSITORY_OWNER if not provided)'
    required: false
  repository:
    description: 'Repository full name owner/repo (optional, will use $GITHUB_REPOSITORY if not provided)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Publish composer package to GitHub Packages
      shell: bash
      run: |
        set -euo pipefail
        # call the extracted script with inputs as args (allows local testing)
        bash "${{ github.action_path }}/.github/actions/github-packages-publish/publish.sh" \
          "${{ inputs.package_zip_path }}" \
          "${{ inputs.github_token }}" \
          "${{ inputs.retries }}" \
          "${{ inputs.backoff_seconds }}" \
          "${{ inputs.repository_owner }}" \
          "${{ inputs.repository }}"
